global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'iris-classifier'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'iris-api'
    static_configs:
      - targets: ['iris-classifier-api:8000']
    metrics_path: '/metrics-prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

